Better error when package config var missing
Before:

```
Error: Options JSON failed validation
Path: environment
```

After:

```
Error: Options JSON failed validation
Required parameter missing: dbHost
Path: environment
```

Fixes: https://dcosjira.atlassian.net/browse/DCOS-191