Show path of config file we're validating
so we know what the active config file is:

```
$ dcos config validate
Validating /Users/abramowi/.dcos/dcos.toml ...
Congratulations, your configuration is valid!

$ dcos config validate
Validating /Users/abramowi/.dcos/dcos.toml ...
Error: Additional properties are not allowed ('prompt_login' was unexpected)
Path: core
Value: {"prompt_login": true, ...}
```