packagemanager: improver error when config variable missing (#908)
Before:

```
Error: Options JSON failed validation
Path: environment
```

After:

```
Error: Options JSON failed validation
Required parameter missing: dbHost
Path: environment
```

Fixes: https://dcosjira.atlassian.net/browse/DCOS-191